package chat.stoat.ui.theme

import androidx.compose.ui.graphics.Color

/**
 * As cores do Callju.
 *
 * Preto de verdade nas superficies (o Material tinge o cinza com a cor de
 * destaque e o resultado puxava para o marrom) e o laranja reservado aos
 * detalhes: botao principal, selecao e afins.
 */
object Colour {
    val Seed = Color(0xFFE8823C)

    val PrimaryLight = Color(0xFFA5500F)
    val OnPrimaryLight = Color(0xFFFFFFFF)
    val PrimaryContainerLight = Color(0xFFFFE0CC)
    val OnPrimaryContainerLight = Color(0xFF5A2A05)
    val InversePrimaryLight = Color(0xFFF3AA73)
    val SecondaryLight = Color(0xFF55565C)
    val OnSecondaryLight = Color(0xFFFFFFFF)
    val SecondaryContainerLight = Color(0xFFEAEAEE)
    val OnSecondaryContainerLight = Color(0xFF2A2A30)
    val TertiaryLight = Color(0xFFA5500F)
    val OnTertiaryLight = Color(0xFFFFFFFF)
    val TertiaryContainerLight = Color(0xFFFFE0CC)
    val OnTertiaryContainerLight = Color(0xFF5A2A05)
    val BackgroundLight = Color(0xFFFBFBFC)
    val OnBackgroundLight = Color(0xFF1B1B1E)
    val SurfaceLight = Color(0xFFFBFBFC)
    val OnSurfaceLight = Color(0xFF1B1B1E)
    val SurfaceVariantLight = Color(0xFFE9E9ED)
    val OnSurfaceVariantLight = Color(0xFF55565C)
    val SurfaceTintLight = Color(0xFFA5500F)
    val InverseSurfaceLight = Color(0xFF2A2A30)
    val InverseOnSurfaceLight = Color(0xFFF2F2F5)
    val ErrorLight = Color(0xFFBA1A1A)
    val OnErrorLight = Color(0xFFFFFFFF)
    val ErrorContainerLight = Color(0xFFFFDAD6)
    val OnErrorContainerLight = Color(0xFF93000A)
    val OutlineLight = Color(0xFF86878E)
    val OutlineVariantLight = Color(0xFFDEDEE3)
    val ScrimLight = Color(0xFF000000)
    val SurfaceBrightLight = Color(0xFFFFFFFF)
    val SurfaceContainerLight = Color(0xFFF1F1F4)
    val SurfaceContainerHighLight = Color(0xFFEBEBEF)
    val SurfaceContainerHighestLight = Color(0xFFE5E5EA)
    val SurfaceContainerLowLight = Color(0xFFF7F7F9)
    val SurfaceContainerLowestLight = Color(0xFFFFFFFF)
    val SurfaceDimLight = Color(0xFFDEDEE3)
    val ShadowLight = Color(0xFF000000)
    val ControlActivatedLight = Color(0xFFFFE0CC)
    val ControlNormalLight = Color(0xFF55565C)
    val ControlHighlightLight = Color(0x1F000000)
    val TextPrimaryInverseLight = Color(0xFFEDEDF0)
    val TextSecondaryAndTertiaryInverseLight = Color(0xFFA3A4AB)
    val TextPrimaryInverseDisableOnlyLight = Color(0xFFEDEDF0)
    val TextSecondaryAndTertiaryInverseDisabledLight = Color(0xFFEDEDF0)
    val TextHintInverseLight = Color(0xFFEDEDF0)

    val PrimaryDark = Color(0xFFF0964F)
    val OnPrimaryDark = Color(0xFF2A1103)
    val PrimaryContainerDark = Color(0xFF1E1E23)
    val OnPrimaryContainerDark = Color(0xFFF3AA73)
    val InversePrimaryDark = Color(0xFFB85A17)
    val SecondaryDark = Color(0xFFC9CAD1)
    val OnSecondaryDark = Color(0xFF24242A)
    val SecondaryContainerDark = Color(0xFF1E1E23)
    val OnSecondaryContainerDark = Color(0xFFE4E4E9)
    val TertiaryDark = Color(0xFFF3AA73)
    val OnTertiaryDark = Color(0xFF2A1103)
    val TertiaryContainerDark = Color(0xFF1E1E23)
    val OnTertiaryContainerDark = Color(0xFFF3AA73)
    val BackgroundDark = Color(0xFF0C0C0E)
    val OnBackgroundDark = Color(0xFFEDEDF0)
    val SurfaceDark = Color(0xFF0C0C0E)
    val OnSurfaceDark = Color(0xFFEDEDF0)
    val SurfaceVariantDark = Color(0xFF24242A)
    val OnSurfaceVariantDark = Color(0xFFA3A4AB)
    val SurfaceTintDark = Color(0xFFE8823C)
    val InverseSurfaceDark = Color(0xFFEDEDF0)
    val InverseOnSurfaceDark = Color(0xFF1C1C20)
    val ErrorDark = Color(0xFFFFB4AB)
    val OnErrorDark = Color(0xFF690005)
    val ErrorContainerDark = Color(0xFF93000A)
    val OnErrorContainerDark = Color(0xFFFFDAD6)
    val OutlineDark = Color(0xFF6E6F77)
    val OutlineVariantDark = Color(0xFF2A2A30)
    val ScrimDark = Color(0xFF000000)
    val SurfaceBrightDark = Color(0xFF2A2A30)
    val SurfaceContainerDark = Color(0xFF151518)
    val SurfaceContainerHighDark = Color(0xFF1C1C20)
    val SurfaceContainerHighestDark = Color(0xFF24242A)
    val SurfaceContainerLowDark = Color(0xFF111113)
    val SurfaceContainerLowestDark = Color(0xFF08080A)
    val SurfaceDimDark = Color(0xFF0C0C0E)
    val ShadowDark = Color(0xFF000000)
    val ControlActivatedDark = Color(0xFF1E1E23)
    val ControlNormalDark = Color(0xFFA3A4AB)
    val ControlHighlightDark = Color(0x33FFFFFF)
    val TextPrimaryInverseDark = Color(0xFF1B1B1E)
    val TextSecondaryAndTertiaryInverseDark = Color(0xFF55565C)
    val TextPrimaryInverseDisableOnlyDark = Color(0xFF1B1B1E)
    val TextSecondaryAndTertiaryInverseDisabledDark = Color(0xFF1B1B1E)
    val TextHintInverseDark = Color(0xFF1B1B1E)

    val PrimaryFixed = Color(0xFFFFE0CC)
    val PrimaryFixedDim = Color(0xFFF3AA73)
    val OnPrimaryFixed = Color(0xFF2A1103)
    val OnPrimaryFixedVariant = Color(0xFF8F4410)
    val SecondaryFixed = Color(0xFFEAEAEE)
    val SecondaryFixedDim = Color(0xFFC9CAD1)
    val OnSecondaryFixed = Color(0xFF1B1B1E)
    val OnSecondaryFixedVariant = Color(0xFF44454B)
    val TertiaryFixed = Color(0xFFFFE0CC)
    val TertiaryFixedDim = Color(0xFFF3AA73)
    val OnTertiaryFixed = Color(0xFF2A1103)
    val OnTertiaryFixedVariant = Color(0xFF8F4410)
    val PrimaryPaletteKeyColor = Color(0xFFE8823C)
    val SecondaryPaletteKeyColor = Color(0xFF86878E)
    val TertiaryPaletteKeyColor = Color(0xFFC97A3E)
    val NeutralPaletteKeyColor = Color(0xFF7A7B82)
    val NeutralVariantPaletteKeyColor = Color(0xFF7A7B82)
    val ErrorPaletteKeyColor = Color(0xFFDE3730)
}
